### ISSUE TITLE
Adaptation to SteamDB site as well.

### ISSUE THREAD

**Issue by DogancanYr** [Altansar69/CS.RIN.RU-Enhanced-external#1]

**Comment by Altansar69** [comment]
? i don't understand the issues

**Comment by DogancanYr** [comment]
There are no new changes. SteamDB doesn't work either.

**Comment by DogancanYr** [comment]
Never mind, just approve the Reddiepoint person's pull request.

**Comment by Altansar69** [comment]
Yeah mb, i think it was already merge
