### ISSUE TITLE
PCGamingWiki

### ISSUE THREAD

**Issue by Altansar69** [Altansar69/CS.RIN.RU-Enhanced-external#10]
Add PCGamingWiki support.

**Comment by Altansar69** [comment]
We can add the button here: 
![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/1b58dac1-c9e5-4b0d-bdd7-411ab7acd6a5)
or here: 
![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/dd1627da-6a3d-496c-85a7-ed882e7657bb)

**Comment by Altansar69** [comment]
exemple page: https://www.pcgamingwiki.com/wiki/War_Hospital

**Comment by wefalltomorrow** [comment]
> Maybe you could even put it in both places 😉

Agreed :)

**Comment by Altansar69** [comment]
Both ???????????
Do you hate me @Reddiepoint ?xD

**Comment by Altansar69** [comment]
@Reddiepoint i create a new branch.
Now we need to do modify addRinButton() and addRinTags() for PCGamingWiki

**Comment by Altansar69** [comment]
I can do this quite easily, but I don't understand the addRinButton and the addRinTags xD

**Comment by Altansar69** [comment]
Seems to works now: 
![image](https://github.com/Altansar69/CS.RIN.RU-Enhanced-external/assets/97360807/c4c48f18-cb9a-4712-a760-b8db35eef880)

**Comment by Altansar69** [comment]
But what should we do with games that aren't on Steam?
Should we try to find them in other ways?

**Comment by wefalltomorrow** [comment]
> But what should we do with games that aren't on Steam? Should we try to find them in other ways?

Seems like a good idea, but how would that be achieved?

**Comment by wefalltomorrow** [comment]
Any updates? :)

**Comment by Altansar69** [comment]
Hum, i think we do it but only on the beta version for now (it's my fault). I go try this week

**Comment by wefalltomorrow** [comment]
> Hum, i think we do it but only on the beta version for now (it's my fault). I go try this week

Cheers!

**Comment by Altansar69** [comment]
> > But what should we do with games that aren't on Steam? Should we try to find them in other ways?
> 
> Seems like a good idea, but how would that be achieved?

idk xD
