### ISSUE TITLE
Also ( support should come.

### ISSUE THREAD

**Issue by DogancanYr** [Altansar69/CS.RIN.RU-Enhanced-external#16]
https://cs.rin.ru/forum/viewtopic.php?f=10&t=87558&hilit=tom+claancy%27s

**Comment by Altansar69** [comment]
We can't do anything about that. They misspelled the tag :/, it should be in square brackets.

**Comment by Altansar69** [comment]
can look that https://cs.rin.ru/forum/viewtopic.php?p=2970171#p2970171
